### ISSUE TITLE
Giving collaborators @nodejs.org emails?

### ISSUE THREAD

**Issue by benjamingr** [nodejs/email#99]
Hey, 

Some platforms (php for example) provide emails that can be used by core members for "official" communication - allowing the creation of special filters to better handle with the emails coming in.

At Node.js - we list the public emails of core collaborators at https://github.com/nodejs/node

It might be useful to allow users to sign up for @nodejs.org emails 

I have found that at the moment only @rvagg does this (here: https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L74 )

Is this something we have a policy on or ever discussed?

**Comment by Trott** [comment]
@benjamingr I'm pretty sure this was discussed at least once in the distant past, but of course, lots has changed since then, so probably worth discussing again.

Here are the concerns that I'd have about doing something like this:

* We have a *lot* of Collaborators compared to other projects. Maintaining the email list is overhead. Is the value worth it?

* Do we want to give someone an email address that imparts on them an implied stamp of official approval for their communications? I'd prefer to go in the *other* direction of making it more clear that people don't speak *for* the project just because they happen to be one of many people who work on it and get to make decisions about it.

**Comment by benjamingr** [comment]
> I'd prefer to go in the other direction of making it more clear that people don't speak for the project just because they happen to be one of many people who work on it and get to make decisions about it.

I definitely agree with that part.

**Comment by mhdawson** [comment]
I agree with the concern about adding additional overhead.  I'm not sure we have the cycles to add an additional thing to manage.

**Comment by Trott** [comment]
Seems like this should be closed at this point, but as always, if I'm mistaken, re-open.
